import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  mainWrapper: {
    flex: 1,
    backgroundColor: '#D4FAFC',
  },
  headerWrapper: {
    height: 250,
    width: '100%',
    backgroundColor: '#146C94',
    alignItems: 'center',
  },
  innerWrapper: {
    alignItems: 'center',
    borderColor: 'red',
    borderWidth: 2,
    height: 80,
    width: 80,
    justifyContent: 'center',
    borderRadius: 10,
    marginTop: 20,
   
  },
  back: {
    width: '100%',
    paddingLeft: 10,
    marginTop: 20,
  },
  mainContent: {
    flex: 1,
    marginTop: 20,
    alignItems: 'center',
    paddingBottom: 30,
  },
  buttonText: {
    fontSize: 15,
    color: 'white',
  },
  btn: {
    width: '80%',
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 10,
    borderRadius: 10,
  },
  vin: {
    width: '80%',
    marginTop: 10,
  },
  input: {
    width: '100%',
    elevation: 10,
    height: 40,
    backgroundColor: 'white',
    borderRadius: 10,
    marginTop: 5,
  },
  date: {
    width: '100%',
    elevation: 10,
    height: 40,
    backgroundColor: 'white',
    borderRadius: 10,
    marginTop: 5,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  right: {
    flex: 1,
    alignItems: 'center',
    flexDirection: 'row',
  },
  left: {
    flex: 1,
    paddingLeft: 10,
    alignItems: 'center',
    flexDirection: 'row',
  },
  location: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
    marginBottom: 10,
  },
  city: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  state: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cityDrop: {
    height: 30,
    width: 110,
    backgroundColor: 'white',
    elevation: 10,
    marginLeft: 10,
  },
  checkList: {
    marginTop: 30,
    width: '100%',
    alignItems: 'center',
  },
  category: {
    width: '80%',
    height: 30,
    backgroundColor: 'gray',
    marginTop: 30,
    justifyContent: 'center',
  },
  qstn: {
    width: '80%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    alignItems: 'center',
  },
  btnWrapper: {
    borderWidth: 2,
    borderColor: 'green',
    width: 90,
    marginRight: 10,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    // marginTop:10
  },
  question: {
    width: '80%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sign: {
    height: 100,
    width: 100,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  signText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 20,
  },
  wrong: {
    borderWidth: 2,
    borderColor: 'red',
    width: 90,
    marginRight: 10,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  na: {
    borderWidth: 2,
    borderColor: 'yellow',
    width: 90,
    marginRight: 10,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  picker: {
    borderWidth: 0,
    // height:30
  },
  picker1: {
    borderWidth: 0,
    marginTop: 5,
    backgroundColor: 'white',
    elevation: 10,
    // height:30,
    marginBottom:10
  },
});